---
- name: Converge
  hosts: all
  gather_facts: true
  pre_tasks:
    - name: "Include diademiemi.epel"
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"

...
