---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Test if EPEL packages are available
      become: true
      ansible.builtin.yum:
        name: chromium
        state: present
